# Generated by Django 5.1.1 on 2024-10-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_shoesentry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoesentry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shoes_images/'),
        ),
    ]
