# Generated by Django 5.1.1 on 2024-10-01 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_shoesentry_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoesentry',
            name='image',
        ),
    ]
